modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "quickfind"
version = "${version}"
displayName = "QuickFind"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
Lightweight vanilla inventory search improvements. [Modrinth](https://modrinth.com/project/quickfind) | [GitHub](https://github.com/manukek/quickfind) | [Issues](https://github.com/manukek/quickfind/issues)
'''

[[dependencies.quickfind]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickfind]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.21.12)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "quickfind.neoforge.mixins.json"
